Added ST_Distance_Sphere and ST_Distance to mysql
creof/doctrine2-spatial pull request #191
Opened 2018-05-19 19:12 UTC by 0x6368

2018-11-16 16:32 UTC, sela commented
when will this be merged?

2018-11-16 16:48 UTC, holtkamp commented
Note sure this is still on the radar for @sadortun ...

2018-11-16 17:00 UTC, sela commented
> Note sure this is still on the radar for @sadortun ...

well i just added the ST_Distance_Sphere internally as needed it calculate distances for my project.

2019-06-17 14:03 UTC, asikrhmn commented
Any plan to merge this?

2022-01-17 16:58 UTC, albertwitrac approved these changes

2023-08-08 09:32 UTC, Mathieu33260 approved these changes

2023-08-08 09:40 UTC, mtexeiraultra approved these changes

2023-08-08 12:08 UTC, sadortun commented on phpunit.xml.dist
> +        <var name="db_password" value="fdklgjhsaljf" />
Not sure this should be modified 🥲

2023-08-08 12:10 UTC, sadortun requested changes
@0x6368 looks good except DB credentials that are now set to some random thing.

2023-09-20 12:03 UTC, merged

2023-09-20 12:04 UTC, sadortun commented
Thanks!